export const CLIENTF_CREATE_REQUEST = 'CLIENTF_CREATE_REQUEST'
export const CLIENTF_CREATE_SUCCESS = 'CLIENTF_CREATE_SUCCESS'
export const CLIENTF_CREATE_FAIL = 'CLIENTF_CREATE_FAIL'
export const CLIENTF_CREATE_RESET = 'CLIENTF_CREATE_RESET'


export const CLIENTF_DELETE_REQUEST = 'CLIENTF_DELETE_REQUEST'
export const CLIENTF_DELETE_SUCCESS = 'CLIENTF_DELETE_SUCCESS'
export const CLIENTF_DELETE_FAIL = 'CLIENTF_DELETE_FAIL'



export const CLIENTF_LIST_REQUEST = 'CLIENTF_LIST_REQUEST'
export const CLIENTF_LIST_SUCCESS = 'CLIENTF_LIST_SUCCESS'
export const CLIENTF_LIST_FAIL = 'CLIENTF_LIST_FAIL'



export const CLIENTF_DETAILS_REQUEST = 'CLIENTF_DETAILS_REQUEST'
export const CLIENTF_DETAILS_SUCCESS = 'CLIENTF_DETAILS_SUCCESS'
export const CLIENTF_DETAILS_FAIL = 'CLIENTF_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const CLIENTF_UPDATE_REQUEST = 'CLIENTF_UPDATE_REQUEST'
export const CLIENTF_UPDATE_SUCCESS = 'CLIENTF_UPDATE_SUCCESS'
export const CLIENTF_UPDATE_FAIL = 'CLIENTF_UPDATE_FAIL'
export const CLIENTF_UPDATE_RESET = 'CLIENTF_UPDATE_RESET'