export const DEVIS_CREATE_REQUEST = 'DEVIS_CREATE_REQUEST'
export const DEVIS_CREATE_SUCCESS = 'DEVIS_CREATE_SUCCESS'
export const DEVIS_CREATE_FAIL = 'DEVIS_CREATE_FAIL'
export const DEVIS_CREATE_RESET = 'DEVIS_CREATE_RESET'


export const DEVIS_DELETE_REQUEST = 'DEVIS_DELETE_REQUEST'
export const DEVIS_DELETE_SUCCESS = 'DEVIS_DELETE_SUCCESS'
export const DEVIS_DELETE_FAIL = 'DEVIS_DELETE_FAIL'



export const DEVIS_LIST_REQUEST = 'DEVIS_LIST_REQUEST'
export const DEVIS_LIST_SUCCESS = 'DEVIS_LIST_SUCCESS'
export const DEVIS_LIST_FAIL = 'DEVIS_LIST_FAIL'



export const DEVIS_DETAILS_REQUEST = 'DEVIS_DETAILS_REQUEST'
export const DEVIS_DETAILS_SUCCESS = 'DEVIS_DETAILS_SUCCESS'
export const DEVIS_DETAILS_FAIL = 'DEVIS_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const DEVIS_UPDATE_REQUEST = 'DEVIS_UPDATE_REQUEST'
export const DEVIS_UPDATE_SUCCESS = 'DEVIS_UPDATE_SUCCESS'
export const DEVIS_UPDATE_FAIL = 'DEVIS_UPDATE_FAIL'
export const DEVIS_UPDATE_RESET = 'DEVIS_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'